name: Run CI
on:
  push:
    branches:
      - main
  workflow_dispatch:
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Check code style
        run: |
          yarn run fmt
          git --no-pager diff --exit-code

      - name: CI tests
        run: yarn run test

      - name: Build
        run: yarn build-only

      - name: web-ext lint
        run: yarn web-ext:lint
